services:
  homeassistant:
    container_name: homeassistant_dev
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - ./neumorphism-cards:/config/www/neumorphism-cards
      - ./themes:/config/themes
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "8123:8123"
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Europe/Madrid
    entrypoint: /entrypoint.sh
